[package]
name = "aoc"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = "0.17.5"
nom = "7"
num = "0.4.0"
pathfinding = "4.3.0"
regex = "1.8.3"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
